#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-desktop
    realname: "User"
    username: n1
    password: "$6$YY0yP14wDrktdZYX$g8J1v9SqL5CSPi9xvwJojZSO4MpY5YOWNOcD1XxfPc9U0ZCla0vE44GywZpDBbX9Z9/JZew.gqRsvHt/wly4S/"

  packages:
    - ubuntu-desktop

  snaps:
    - name: firefox
    - name: gnome-3-38-2004
    - name: gtk-common-themes
    - name: snap-store
    - name: snapd-desktop-integration
    - name: code

  network:
  version: 2
  renderer: NetworkManager
  wifis:
    wlo1:
      dhcp4: true
      access-points:
        "Galaxy":
          password: "12345678"

  storage:
    layout:
      name: direct
